language: python
python:
  - "2.7"

# command to install dependencies
#install: "pip install -r requirements.txt"
sudo: required

services:
  - docker

before_install:
  - docker build -t operationzombie/base image/

install:
  - docker run -d -p 80:80 --name ozc operationzombie/base
# command to run tests
script: 
  - docker ps | grep -q base

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push operationzombie/base

notifications:
  slack:
    rooms:
    - undeadbaby:o1qjQIY53FyeTPFy5bCfan9n#random
    on_success: change
    on_failure: always
